### ISSUE TITLE
[feat] Backend logger

### ISSUE THREAD

**Issue by OvilashMoitra** [idurar/erp-crm#321]
Can I set winston logger in the backend?

**Comment by salahlalami** [comment]
@OvilashMoitra you are welcome to do that

**Comment by adnan-abdullah1** [comment]
> What kind of logs you will save!

**Comment by parteekcoder** [comment]
> What kind of logs you will save!

@salahlalami @adnan-abdullah1 that logs will be of the API responses we are sending , so that we can track broken responses and fix them.

Should I go ahead to implement this  @salahlalami

**Comment by dhrumitpatel48** [comment]
> > What kind of logs you will save!

@salahlalami @adnan-abdullah1 

Backend debugging will be a lot easier after implementing logs. One should keep in mind that any secret/private/special info should NOT be added to logs.

Basically, logs should have all the info by which it will be easy to track the flow of requests/responses so that if any issue occurs/found then quickly we can identify where is the issue and probably what is the issue. Sometimes we can find solutions easily from logs only. 

Initially,
We can store log files in MongoDB as well. So no extra costs. Also, logs can be stored in container volume as well so that there will be no costs.

After then we can opt for other solutions like cloud (e.g., AWS, Azure, Google Cloud),  ELK Stack (Elasticsearch, Logstash, Kibana) and others tools as well. There all require extra costs.

**Comment by parteekcoder** [comment]
> We can store log files in MongoDB as well. So no extra costs. Also, logs can be stored in container volume as well so that there will be no costs.

Storing logs in container volumes or MongoDB is a good idea in the context of cost but it will be difficult to monitor/debug the `error` logs. With that, we need to create a user interface that will help to see and analyze the logs collected in the database

**Comment by dhrumitpatel48** [comment]
> > We can store log files in MongoDB as well. So no extra costs. Also, logs can be stored in container volume as well so that there will be no costs.
> 
> Storing logs in container volumes or MongoDB is a good idea in the context of cost but it will be difficult to monitor/debug the `error` logs. With that, we need to create a user interface that will help to see and analyze the logs collected in the database

As of now, it is not an extreme requirement from customers that they want logs, they want to analyze logs. It is not like that.

We are not implementing a Logger for data collection or data analysis. We are implementing a logger for better debugging and a better way to issue finding and issues fixing.

So anyhow, we need a simple log file or txt file containing which contains logs.

As of now, to start implementing logs this is enough I guess.

What's your take on this @salahlalami ??

**Comment by Zewenaco** [comment]
Hello, I'd like to contribute in this project, Is anyone there working in this feature?. If not I would like to try it ✌️

**Comment by adnan-abdullah1** [comment]
Logs could be stored in Elastic, 
Basically EFK (elastic Fluetend and kibana) 
could be utilized
